var toc = {"link":"toc","title":"toc","children":[{"link":"null","title":"UnityEditor","children":
	[
		{"link":"null","title":"UnityEditor.Advertisements","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Advertisements.AdvertisementSettings","title":"AdvertisementSettings","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.AI","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"AI.NavMeshBuilder","title":"NavMeshBuilder","children":null},
			{"link":"AI.NavMeshVisualizationSettings","title":"NavMeshVisualizationSettings","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Analytics","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Analytics.AnalyticsSettings","title":"AnalyticsSettings","children":null},
			{"link":"Analytics.PerformanceReportingSettings","title":"PerformanceReportingSettings","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.AnimatedValues","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"AnimatedValues.AnimBool","title":"AnimBool","children":null},
			{"link":"AnimatedValues.AnimFloat","title":"AnimFloat","children":null},
			{"link":"AnimatedValues.AnimQuaternion","title":"AnimQuaternion","children":null},
			{"link":"AnimatedValues.AnimVector3","title":"AnimVector3","children":null},
			{"link":"AnimatedValues.BaseAnimValue_1","title":"BaseAnimValue<T0>","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Animations","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Animations.AnimatorCondition","title":"AnimatorCondition","children":null},
			{"link":"Animations.AnimatorController","title":"AnimatorController","children":null},
			{"link":"Animations.AnimatorControllerLayer","title":"AnimatorControllerLayer","children":null},
			{"link":"Animations.AnimatorState","title":"AnimatorState","children":null},
			{"link":"Animations.AnimatorStateMachine","title":"AnimatorStateMachine","children":null},
			{"link":"Animations.AnimatorStateTransition","title":"AnimatorStateTransition","children":null},
			{"link":"Animations.AnimatorTransition","title":"AnimatorTransition","children":null},
			{"link":"Animations.AnimatorTransitionBase","title":"AnimatorTransitionBase","children":null},
			{"link":"Animations.BlendTree","title":"BlendTree","children":null},
			{"link":"Animations.ChildAnimatorState","title":"ChildAnimatorState","children":null},
			{"link":"Animations.ChildAnimatorStateMachine","title":"ChildAnimatorStateMachine","children":null},
			{"link":"Animations.ChildMotion","title":"ChildMotion","children":null},
			{"link":"Animations.StateMachineBehaviourContext","title":"StateMachineBehaviourContext","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"Animations.AnimatorConditionMode","title":"AnimatorConditionMode","children":null},
			{"link":"Animations.AnimatorLayerBlendingMode","title":"AnimatorLayerBlendingMode","children":null},
			{"link":"Animations.BlendTreeType","title":"BlendTreeType","children":null},
			{"link":"Animations.TransitionInterruptionSource","title":"TransitionInterruptionSource","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Build","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Build.BuildFailedException","title":"BuildFailedException","children":null}
		]
	},
	{"link":"null","title":"Interfaces","children":
		[
					{"link":"Build.IOrderedCallback","title":"IOrderedCallback","children":null},
			{"link":"Build.IPostprocessBuild","title":"IPostprocessBuild","children":null},
			{"link":"Build.IPreprocessBuild","title":"IPreprocessBuild","children":null},
			{"link":"Build.IProcessScene","title":"IProcessScene","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Callbacks","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Callbacks.DidReloadScripts","title":"DidReloadScripts","children":null}
		]
	},
	{"link":"null","title":"Attributes","children":
		[
					{"link":"Callbacks.OnOpenAssetAttribute","title":"OnOpenAssetAttribute","children":null},
			{"link":"Callbacks.PostProcessBuildAttribute","title":"PostProcessBuildAttribute","children":null},
			{"link":"Callbacks.PostProcessSceneAttribute","title":"PostProcessSceneAttribute","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.CrashReporting","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"CrashReporting.CrashReportingSettings","title":"CrashReportingSettings","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Events","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Events.UnityEventTools","title":"UnityEventTools","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.EventSystems","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"EventSystems.EventSystemEditor","title":"EventSystemEditor","children":null},
			{"link":"EventSystems.EventTriggerEditor","title":"EventTriggerEditor","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.IMGUI","children":
		[
				{"link":"null","title":"UnityEditor.IMGUI.Controls","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"IMGUI.Controls.BoxBoundsHandle","title":"BoxBoundsHandle","children":null},
				{"link":"IMGUI.Controls.CapsuleBoundsHandle","title":"CapsuleBoundsHandle","children":
					[
									{"link":"null","title":"Enumerations","children":
					[
											{"link":"IMGUI.Controls.CapsuleBoundsHandle.HeightAxis","title":"HeightAxis","children":null}
					]
				}
					]
				},
				{"link":"IMGUI.Controls.MultiColumnHeader","title":"MultiColumnHeader","children":
					[
									{"link":"null","title":"Classes","children":
					[
											{"link":"IMGUI.Controls.MultiColumnHeader.DefaultGUI","title":"DefaultGUI","children":null},
						{"link":"IMGUI.Controls.MultiColumnHeader.DefaultStyles","title":"DefaultStyles","children":null}
					]
				}
					]
				},
				{"link":"IMGUI.Controls.MultiColumnHeaderState","title":"MultiColumnHeaderState","children":
					[
									{"link":"null","title":"Classes","children":
					[
											{"link":"IMGUI.Controls.MultiColumnHeaderState.Column","title":"Column","children":null}
					]
				}
					]
				},
				{"link":"IMGUI.Controls.PrimitiveBoundsHandle","title":"PrimitiveBoundsHandle","children":
					[
									{"link":"null","title":"Enumerations","children":
					[
											{"link":"IMGUI.Controls.PrimitiveBoundsHandle.Axes","title":"Axes","children":null},
						{"link":"IMGUI.Controls.PrimitiveBoundsHandle.HandleDirection","title":"HandleDirection","children":null}
					]
				}
					]
				},
				{"link":"IMGUI.Controls.SearchField","title":"SearchField","children":null},
				{"link":"IMGUI.Controls.SphereBoundsHandle","title":"SphereBoundsHandle","children":null},
				{"link":"IMGUI.Controls.TreeView","title":"TreeView","children":
					[
									{"link":"null","title":"Classes","children":
					[
											{"link":"IMGUI.Controls.TreeView.CanStartDragArgs","title":"CanStartDragArgs","children":null},
						{"link":"IMGUI.Controls.TreeView.DefaultGUI","title":"DefaultGUI","children":null},
						{"link":"IMGUI.Controls.TreeView.DefaultStyles","title":"DefaultStyles","children":null},
						{"link":"IMGUI.Controls.TreeView.DragAndDropArgs","title":"DragAndDropArgs","children":null},
						{"link":"IMGUI.Controls.TreeView.RenameEndedArgs","title":"RenameEndedArgs","children":null},
						{"link":"IMGUI.Controls.TreeView.RowGUIArgs","title":"RowGUIArgs","children":null},
						{"link":"IMGUI.Controls.TreeView.SetupDragAndDropArgs","title":"SetupDragAndDropArgs","children":null}
					]
				},
				{"link":"null","title":"Enumerations","children":
					[
											{"link":"IMGUI.Controls.TreeView.DragAndDropPosition","title":"DragAndDropPosition","children":null}
					]
				}
					]
				},
				{"link":"IMGUI.Controls.TreeViewItem","title":"TreeViewItem","children":null},
				{"link":"IMGUI.Controls.TreeViewState","title":"TreeViewState","children":null}
			]
		},
		{"link":"null","title":"Enumerations","children":
			[
							{"link":"IMGUI.Controls.TreeViewSelectionOptions","title":"TreeViewSelectionOptions","children":null}
			]
		}
			]
		}
		]
	},
	{"link":"null","title":"UnityEditor.iOS","children":
		[
				{"link":"null","title":"UnityEditor.iOS.Xcode","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"iOS.Xcode.PBXProject","title":"PBXProject","children":null},
				{"link":"iOS.Xcode.PlistDocument","title":"PlistDocument","children":null},
				{"link":"iOS.Xcode.PlistElement","title":"PlistElement","children":null},
				{"link":"iOS.Xcode.PlistElementArray","title":"PlistElementArray","children":null},
				{"link":"iOS.Xcode.PlistElementBoolean","title":"PlistElementBoolean","children":null},
				{"link":"iOS.Xcode.PlistElementDict","title":"PlistElementDict","children":null},
				{"link":"iOS.Xcode.PlistElementInteger","title":"PlistElementInteger","children":null},
				{"link":"iOS.Xcode.PlistElementString","title":"PlistElementString","children":null}
			]
		},
		{"link":"null","title":"Enumerations","children":
			[
							{"link":"iOS.Xcode.PBXSourceTree","title":"PBXSourceTree","children":null}
			]
		}
			]
		}
		]
	},
	{"link":"null","title":"UnityEditor.MemoryProfiler","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"MemoryProfiler.Connection","title":"Connection","children":null},
			{"link":"MemoryProfiler.FieldDescription","title":"FieldDescription","children":null},
			{"link":"MemoryProfiler.MemorySection","title":"MemorySection","children":null},
			{"link":"MemoryProfiler.MemorySnapshot","title":"MemorySnapshot","children":null},
			{"link":"MemoryProfiler.PackedGCHandle","title":"PackedGCHandle","children":null},
			{"link":"MemoryProfiler.PackedMemorySnapshot","title":"PackedMemorySnapshot","children":null},
			{"link":"MemoryProfiler.PackedNativeType","title":"PackedNativeType","children":null},
			{"link":"MemoryProfiler.PackedNativeUnityEngineObject","title":"PackedNativeUnityEngineObject","children":null},
			{"link":"MemoryProfiler.TypeDescription","title":"TypeDescription","children":null},
			{"link":"MemoryProfiler.VirtualMachineInformation","title":"VirtualMachineInformation","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Networking","children":
		[
				{"link":"null","title":"UnityEditor.Networking.PlayerConnection","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"Networking.PlayerConnection.ConnectedPlayer","title":"ConnectedPlayer","children":null},
				{"link":"Networking.PlayerConnection.EditorConnection","title":"EditorConnection","children":null}
			]
		}
			]
		}
		]
	},
	{"link":"null","title":"UnityEditor.Purchasing","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Purchasing.PurchasingSettings","title":"PurchasingSettings","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Rendering","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Rendering.AlbedoSwatchInfo","title":"AlbedoSwatchInfo","children":null},
			{"link":"Rendering.EditorGraphicsSettings","title":"EditorGraphicsSettings","children":null},
			{"link":"Rendering.PlatformShaderSettings","title":"PlatformShaderSettings","children":null},
			{"link":"Rendering.TierSettings","title":"TierSettings","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"Rendering.ShaderQuality","title":"ShaderQuality","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.SceneManagement","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"SceneManagement.EditorSceneManager","title":"EditorSceneManager","children":null},
			{"link":"SceneManagement.SceneSetup","title":"SceneSetup","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"SceneManagement.NewSceneMode","title":"NewSceneMode","children":null},
			{"link":"SceneManagement.NewSceneSetup","title":"NewSceneSetup","children":null},
			{"link":"SceneManagement.OpenSceneMode","title":"OpenSceneMode","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.Sprites","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"Sprites.AtlasSettings","title":"AtlasSettings","children":null},
			{"link":"Sprites.Packer","title":"Packer","children":
				[
							{"link":"null","title":"Enumerations","children":
				[
									{"link":"Sprites.Packer.Execution","title":"Execution","children":null}
				]
			}
				]
			},
			{"link":"Sprites.PackerJob","title":"PackerJob","children":null},
			{"link":"Sprites.SpriteUtility","title":"SpriteUtility","children":null}
		]
	},
	{"link":"null","title":"Interfaces","children":
		[
					{"link":"Sprites.IPackerPolicy","title":"IPackerPolicy","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.UI","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"UI.AnimationTriggersDrawer","title":"AnimationTriggersDrawer","children":null},
			{"link":"UI.AspectRatioFitterEditor","title":"AspectRatioFitterEditor","children":null},
			{"link":"UI.ButtonEditor","title":"ButtonEditor","children":null},
			{"link":"UI.CanvasScalerEditor","title":"CanvasScalerEditor","children":null},
			{"link":"UI.ColorBlockDrawer","title":"ColorBlockDrawer","children":null},
			{"link":"UI.ContentSizeFitterEditor","title":"ContentSizeFitterEditor","children":null},
			{"link":"UI.DropdownEditor","title":"DropdownEditor","children":null},
			{"link":"UI.FontDataDrawer","title":"FontDataDrawer","children":null},
			{"link":"UI.GraphicEditor","title":"GraphicEditor","children":null},
			{"link":"UI.GridLayoutGroupEditor","title":"GridLayoutGroupEditor","children":null},
			{"link":"UI.HorizontalOrVerticalLayoutGroupEditor","title":"HorizontalOrVerticalLayoutGroupEditor","children":null},
			{"link":"UI.ImageEditor","title":"ImageEditor","children":null},
			{"link":"UI.InputFieldEditor","title":"InputFieldEditor","children":null},
			{"link":"UI.LayoutElementEditor","title":"LayoutElementEditor","children":null},
			{"link":"UI.MaskEditor","title":"MaskEditor","children":null},
			{"link":"UI.NavigationDrawer","title":"NavigationDrawer","children":null},
			{"link":"UI.RawImageEditor","title":"RawImageEditor","children":null},
			{"link":"UI.RectMask2DEditor","title":"RectMask2DEditor","children":null},
			{"link":"UI.ScrollbarEditor","title":"ScrollbarEditor","children":null},
			{"link":"UI.ScrollRectEditor","title":"ScrollRectEditor","children":null},
			{"link":"UI.SelectableEditor","title":"SelectableEditor","children":null},
			{"link":"UI.SelfControllerEditor","title":"SelfControllerEditor","children":null},
			{"link":"UI.SliderEditor","title":"SliderEditor","children":null},
			{"link":"UI.SpriteStateDrawer","title":"SpriteStateDrawer","children":null},
			{"link":"UI.TextEditor","title":"TextEditor","children":null},
			{"link":"UI.ToggleEditor","title":"ToggleEditor","children":null}
		]
	}
		]
	},
	{"link":"null","title":"UnityEditor.VersionControl","children":
		[
			{"link":"null","title":"Classes","children":
		[
					{"link":"VersionControl.Asset","title":"Asset","children":
				[
							{"link":"null","title":"Enumerations","children":
				[
									{"link":"VersionControl.Asset.States","title":"States","children":null}
				]
			}
				]
			},
			{"link":"VersionControl.AssetList","title":"AssetList","children":null},
			{"link":"VersionControl.ChangeSet","title":"ChangeSet","children":null},
			{"link":"VersionControl.ChangeSets","title":"ChangeSets","children":null},
			{"link":"VersionControl.ConfigField","title":"ConfigField","children":null},
			{"link":"VersionControl.Message","title":"Message","children":
				[
							{"link":"null","title":"Enumerations","children":
				[
									{"link":"VersionControl.Message.Severity","title":"Severity","children":null}
				]
			}
				]
			},
			{"link":"VersionControl.Plugin","title":"Plugin","children":null},
			{"link":"VersionControl.Provider","title":"Provider","children":null},
			{"link":"VersionControl.Task","title":"Task","children":null}
		]
	},
	{"link":"null","title":"Enumerations","children":
		[
					{"link":"VersionControl.CheckoutMode","title":"CheckoutMode","children":null},
			{"link":"VersionControl.CompletionAction","title":"CompletionAction","children":null},
			{"link":"VersionControl.FileMode","title":"FileMode","children":null},
			{"link":"VersionControl.MergeMethod","title":"MergeMethod","children":null},
			{"link":"VersionControl.OnlineState","title":"OnlineState","children":null},
			{"link":"VersionControl.ResolveMethod","title":"ResolveMethod","children":null},
			{"link":"VersionControl.RevertMode","title":"RevertMode","children":null},
			{"link":"VersionControl.SubmitResult","title":"SubmitResult","children":null}
		]
	}
		]
	},
{"link":"null","title":"Classes","children":
	[
			{"link":"AlphabeticalSort","title":"AlphabeticalSort","children":null},
		{"link":"AnimationClipCurveData","title":"AnimationClipCurveData","children":null},
		{"link":"AnimationMode","title":"AnimationMode","children":null},
		{"link":"AnimationUtility","title":"AnimationUtility","children":
			[
					{"link":"null","title":"Enumerations","children":
			[
							{"link":"AnimationUtility.CurveModifiedType","title":"CurveModifiedType","children":null},
				{"link":"AnimationUtility.TangentMode","title":"TangentMode","children":null}
			]
		}
			]
		},
		{"link":"ArrayUtility","title":"ArrayUtility","children":null},
		{"link":"AssetBundleBuild","title":"AssetBundleBuild","children":null},
		{"link":"AssetDatabase","title":"AssetDatabase","children":null},
		{"link":"AssetImporter","title":"AssetImporter","children":null},
		{"link":"AssetModificationProcessor","title":"AssetModificationProcessor","children":null},
		{"link":"AssetPostprocessor","title":"AssetPostprocessor","children":null},
		{"link":"AssetPreview","title":"AssetPreview","children":null},
		{"link":"AudioCurveRendering","title":"AudioCurveRendering","children":null},
		{"link":"AudioImporter","title":"AudioImporter","children":null},
		{"link":"AudioImporterSampleSettings","title":"AudioImporterSampleSettings","children":null},
		{"link":"BaseHierarchySort","title":"BaseHierarchySort","children":null},
		{"link":"BuildPipeline","title":"BuildPipeline","children":null},
		{"link":"BuildPlayerOptions","title":"BuildPlayerOptions","children":null},
		{"link":"ClipAnimationInfoCurve","title":"ClipAnimationInfoCurve","children":null},
		{"link":"ColorPickerHDRConfig","title":"ColorPickerHDRConfig","children":null},
		{"link":"DDSImporter","title":"DDSImporter","children":null},
		{"link":"DecoratorDrawer","title":"DecoratorDrawer","children":null},
		{"link":"DefaultAsset","title":"DefaultAsset","children":null},
		{"link":"DragAndDrop","title":"DragAndDrop","children":null},
		{"link":"Editor","title":"Editor","children":null},
		{"link":"EditorApplication","title":"EditorApplication","children":null},
		{"link":"EditorBuildSettings","title":"EditorBuildSettings","children":null},
		{"link":"EditorBuildSettingsScene","title":"EditorBuildSettingsScene","children":null},
		{"link":"EditorCurveBinding","title":"EditorCurveBinding","children":null},
		{"link":"EditorGUI","title":"EditorGUI","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"EditorGUI.ChangeCheckScope","title":"ChangeCheckScope","children":null},
				{"link":"EditorGUI.DisabledGroupScope","title":"DisabledGroupScope","children":null},
				{"link":"EditorGUI.DisabledScope","title":"DisabledScope","children":null},
				{"link":"EditorGUI.PropertyScope","title":"PropertyScope","children":null}
			]
		}
			]
		},
		{"link":"EditorGUILayout","title":"EditorGUILayout","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"EditorGUILayout.FadeGroupScope","title":"FadeGroupScope","children":null},
				{"link":"EditorGUILayout.HorizontalScope","title":"HorizontalScope","children":null},
				{"link":"EditorGUILayout.ScrollViewScope","title":"ScrollViewScope","children":null},
				{"link":"EditorGUILayout.ToggleGroupScope","title":"ToggleGroupScope","children":null},
				{"link":"EditorGUILayout.VerticalScope","title":"VerticalScope","children":null}
			]
		}
			]
		},
		{"link":"EditorGUIUtility","title":"EditorGUIUtility","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"EditorGUIUtility.IconSizeScope","title":"IconSizeScope","children":null}
			]
		}
			]
		},
		{"link":"EditorJsonUtility","title":"EditorJsonUtility","children":null},
		{"link":"EditorPrefs","title":"EditorPrefs","children":null},
		{"link":"EditorStyles","title":"EditorStyles","children":null},
		{"link":"EditorUserBuildSettings","title":"EditorUserBuildSettings","children":null},
		{"link":"EditorUtility","title":"EditorUtility","children":null},
		{"link":"EditorWindow","title":"EditorWindow","children":null},
		{"link":"FileUtil","title":"FileUtil","children":null},
		{"link":"GameObjectUtility","title":"GameObjectUtility","children":null},
		{"link":"GenericMenu","title":"GenericMenu","children":null},
		{"link":"GUIDrawer","title":"GUIDrawer","children":null},
		{"link":"Handles","title":"Handles","children":
			[
					{"link":"null","title":"Classes","children":
			[
							{"link":"Handles.DrawingScope","title":"DrawingScope","children":null}
			]
		}
			]
		},
		{"link":"HandleUtility","title":"HandleUtility","children":null},
		{"link":"Help","title":"Help","children":null},
		{"link":"Highlighter","title":"Highlighter","children":null},
		{"link":"IHVImageFormatImporter","title":"IHVImageFormatImporter","children":null},
		{"link":"iOSDeviceRequirement","title":"iOSDeviceRequirement","children":null},
		{"link":"LightingDataAsset","title":"LightingDataAsset","children":null},
		{"link":"LightmapEditorSettings","title":"LightmapEditorSettings","children":
			[
					{"link":"null","title":"Enumerations","children":
			[
							{"link":"LightmapEditorSettings.GIBakeBackend","title":"GIBakeBackend","children":null},
				{"link":"LightmapEditorSettings.PathTracerFilter","title":"PathTracerFilter","children":null},
				{"link":"LightmapEditorSettings.PathTracerFilterMode","title":"PathTracerFilterMode","children":null},
				{"link":"LightmapEditorSettings.PathTracerSampling","title":"PathTracerSampling","children":null}
			]
		}
			]
		},
		{"link":"LightmapParameters","title":"LightmapParameters","children":null},
		{"link":"Lightmapping","title":"Lightmapping","children":
			[
					{"link":"null","title":"Enumerations","children":
			[
							{"link":"Lightmapping.GIWorkflowMode","title":"GIWorkflowMode","children":null}
			]
		}
			]
		}
	]
},
{"link":"null","title":"Enumerations","children":
	[
			{"link":"ActionOnDotNetUnhandledException","title":"ActionOnDotNetUnhandledException","children":null},
		{"link":"AndroidBuildSystem","title":"AndroidBuildSystem","children":null},
		{"link":"AndroidBuildType","title":"AndroidBuildType","children":null},
		{"link":"AndroidGamepadSupportLevel","title":"AndroidGamepadSupportLevel","children":null},
		{"link":"AndroidPreferredInstallLocation","title":"AndroidPreferredInstallLocation","children":null},
		{"link":"AndroidSdkVersions","title":"AndroidSdkVersions","children":null},
		{"link":"AndroidShowActivityIndicatorOnLoading","title":"AndroidShowActivityIndicatorOnLoading","children":null},
		{"link":"AndroidSplashScreenScale","title":"AndroidSplashScreenScale","children":null},
		{"link":"AndroidTargetDevice","title":"AndroidTargetDevice","children":null},
		{"link":"ApiCompatibilityLevel","title":"ApiCompatibilityLevel","children":null},
		{"link":"AscentCalculationMode","title":"AscentCalculationMode","children":null},
		{"link":"AspectRatio","title":"AspectRatio","children":null},
		{"link":"AssetDeleteResult","title":"AssetDeleteResult","children":null},
		{"link":"AssetMoveResult","title":"AssetMoveResult","children":null},
		{"link":"AudioSampleRateSetting","title":"AudioSampleRateSetting","children":null},
		{"link":"BuildAssetBundleOptions","title":"BuildAssetBundleOptions","children":null},
		{"link":"BuildOptions","title":"BuildOptions","children":null},
		{"link":"BuildTarget","title":"BuildTarget","children":null},
		{"link":"BuildTargetGroup","title":"BuildTargetGroup","children":null},
		{"link":"ClipAnimationMaskType","title":"ClipAnimationMaskType","children":null},
		{"link":"D3D11FullscreenMode","title":"D3D11FullscreenMode","children":null},
		{"link":"D3D9FullscreenMode","title":"D3D9FullscreenMode","children":null},
		{"link":"DragAndDropVisualMode","title":"DragAndDropVisualMode","children":null},
		{"link":"DrawCameraMode","title":"DrawCameraMode","children":null},
		{"link":"EditorSelectedRenderState","title":"EditorSelectedRenderState","children":null},
		{"link":"EditorSkin","title":"EditorSkin","children":null},
		{"link":"ExportPackageOptions","title":"ExportPackageOptions","children":null},
		{"link":"FontRenderingMode","title":"FontRenderingMode","children":null},
		{"link":"FontTextureCase","title":"FontTextureCase","children":null},
		{"link":"GizmoType","title":"GizmoType","children":null},
		{"link":"GraphicsJobMode","title":"GraphicsJobMode","children":null},
		{"link":"HighlightSearchMode","title":"HighlightSearchMode","children":null},
		{"link":"ImportAssetOptions","title":"ImportAssetOptions","children":null},
		{"link":"iOSAppInBackgroundBehavior","title":"iOSAppInBackgroundBehavior","children":null},
		{"link":"iOSBackgroundMode","title":"iOSBackgroundMode","children":null},
		{"link":"iOSBuildType","title":"iOSBuildType","children":null},
		{"link":"iOSSdkVersion","title":"iOSSdkVersion","children":null},
		{"link":"iOSShowActivityIndicatorOnLoading","title":"iOSShowActivityIndicatorOnLoading","children":null},
		{"link":"iOSStatusBarStyle","title":"iOSStatusBarStyle","children":null},
		{"link":"iOSTargetDevice","title":"iOSTargetDevice","children":null},
		{"link":"iOSTargetOSVersion","title":"iOSTargetOSVersion","children":null},
		{"link":"LightmapBakeQuality","title":"LightmapBakeQuality","children":null}
	]
},
{"link":"null","title":"Attributes","children":
	[
			{"link":"CallbackOrderAttribute","title":"CallbackOrderAttribute","children":null},
		{"link":"CanEditMultipleObjects","title":"CanEditMultipleObjects","children":null},
		{"link":"CustomEditor","title":"CustomEditor","children":null},
		{"link":"CustomPreviewAttribute","title":"CustomPreviewAttribute","children":null},
		{"link":"CustomPropertyDrawer","title":"CustomPropertyDrawer","children":null},
		{"link":"DrawGizmo","title":"DrawGizmo","children":null},
		{"link":"InitializeOnLoadAttribute","title":"InitializeOnLoadAttribute","children":null},
		{"link":"InitializeOnLoadMethodAttribute","title":"InitializeOnLoadMethodAttribute","children":null}
	]
}
	]
},{"link":"null","title":"UnityEngine","children":
	[
		{"link":"null","title":"UnityEngine.UI","children":null}
	]
},{"link":"null","title":"Other","children":
	[
	{"link":"null","title":"Classes","children":
	[
			{"link":"Array","title":"Array","children":null},
		{"link":"Hashtable","title":"Hashtable","children":null},
		{"link":"NonSerializable","title":"NonSerializable","children":null},
		{"link":"Path","title":"Path","children":null},
		{"link":"Serializable","title":"Serializable","children":null},
		{"link":"String","title":"String","children":null}
	]
}
	]
},{"link":"PlayerSettings","title":"PlayerSettings","children":
	[
	{"link":"null","title":"Classes","children":
	[
			{"link":"PlayerSettings.PS4","title":"PS4","children":
			[
					{"link":"null","title":"Enumerations","children":
			[
							{"link":"PlayerSettings.PS4.PS4AppCategory","title":"PS4AppCategory","children":null},
				{"link":"PlayerSettings.PS4.PS4EnterButtonAssignment","title":"PS4EnterButtonAssignment","children":null},
				{"link":"PlayerSettings.PS4.PS4RemotePlayKeyAssignment","title":"PS4RemotePlayKeyAssignment","children":null}
			]
		}
			]
		},
		{"link":"PlayerSettings.PSVita","title":"PSVita","children":
			[
					{"link":"null","title":"Enumerations","children":
			[
							{"link":"PlayerSettings.PSVita.PSVitaAppCategory","title":"PSVitaAppCategory","children":null},
				{"link":"PlayerSettings.PSVita.PSVitaDRMType","title":"PSVitaDRMType","children":null},
				{"link":"PlayerSettings.PSVita.PSVitaEnterButtonAssignment","title":"PSVitaEnterButtonAssignment","children":null},
				{"link":"PlayerSettings.PSVita.PSVitaPowerMode","title":"PSVitaPowerMode","children":null},
				{"link":"PlayerSettings.PSVita.PSVitaTvBootMode","title":"PSVitaTvBootMode","children":null}
			]
		}
			]
		},
		{"link":"PlayerSettings.SamsungTV","title":"SamsungTV","children":
			[
					{"link":"null","title":"Enumerations","children":
			[
							{"link":"PlayerSettings.SamsungTV.SamsungTVProductCategories","title":"SamsungTVProductCategories","children":null}
			]
		}
			]
		}
	]
}
	]
}]}